### ISSUE TITLE
I'm interested in participating!

### ISSUE THREAD

**Issue by dinigi** [DataChallenge-N/FS22#4] opened 2022-04-25 08:16 UTC
### Name

Diego Gil

### ZHAW Username

gilcodie

### Your status at ZHAW (optional)

Bachelor student

### Your institute (optional)

IUNR Institut für Umwelt und Natürliche Ressourcen

**Comment by ratnanil** [comment] 2022-04-29 12:50
Dear Diego

It would be really cool if you participate in the data challenge. I've added some slides on the nature of the data, you can see these slides here: [datachallenge-n.github.io/data](https://datachallenge-n.github.io/data)

Regrettably, this dataset is not open, and we would need you to fill out a non-disclosure agreement before we can send you the data. Can you fill out [this  NDA](https://github.com/DataChallenge-N/FS22/files/8590871/NDA.pdf) and send it back to me (you can also send it via mail to rata@zhaw.ch)?

We are looking forward to this event!

Cheers,

Nils

**Comment by ratnanil** [comment] 2022-05-05 08:01
Dear Diego, I haven't received the NDA back from you yet. Are you still interested in participating?

**Comment by ratnanil** [comment] 2022-05-05 09:33
Thank you for sending us your NDA. I've sent you the data via mail, did you receive it? If so, your next steps are the following:

1. use our [template repo](https://github.com/DataChallenge-N/Project-template) to create a new repository on GitHub

![image](https://user-images.githubusercontent.com/12532091/166877929-ac949a4d-e0ff-406c-91bc-51beebf05531.png)

2. Add a meaningful name and description, then click on *Create repository from template*

![image](https://user-images.githubusercontent.com/12532091/166878359-e76b30a2-9bb2-4107-a7f4-8fd3bbadfb43.png)

3. Copy the URL to your Github Repo and **paste it as a reply to this post**.

![image](https://user-images.githubusercontent.com/12532091/166878921-a9dfd0dd-c0fa-4891-aa87-31e104eded00.png)

4. Open RStudio, Choose *File > New Project > Version Control > Git*. Paste the URL of your Repo 

![image](https://user-images.githubusercontent.com/12532091/166879170-02b0db56-1101-4814-8c24-c938df0830d8.png)

5. Create a new folder in your project called `data` and add the roe deer data we sent you. The content of `data` will not be uploaded to GitHub, since the folder is listed in the file `.gitignore`.

**Comment by ratnanil** [comment] 2022-05-05 12:26
If you have **any questions**, we can schedule [a meeting](https://calendly.com/rata-zhaw/)

**Comment by ratnanil** [comment] 2022-05-13 13:25
I had initially sent you the data via mail. I've had to update the data slightly (added information on the sex of each roe deer), and instead of resending you the data, I've created a private repo holding the data and sent you an invitation for read access to this repo. After accepting this invitation, you will find the roe deer data here: https://github.com/DataChallenge-N/FS22_data

**Comment by dinigi** [comment] 2022-05-13 14:49
cheers

**Comment by dinigi** [comment] 2022-06-10 16:11
https://github.com/dinigi/datachallenge22-deer/

**Comment by ratnanil** [comment] 2022-06-13 12:57
Thank you for submitting your DataChallenge URL. I will have a look into it shortly!

**Comment by ratnanil** [comment] 2022-06-15 12:19
It seems you have yet only created the research proposal, but not written any code yet. Is this correct?

**Comment by dinigi** [comment] 2022-06-15 12:26
Hi Nils, no I have not written any code yet. I thought the idea was to do
this next week

**Comment by ratnanil** [comment] 2022-06-15 12:58
Not quite! The idea was that you:

> use your coding skills to do an exploratory analysis and come up with an idea on what you want to further explore with this data. [...]  You submit this idea individually or in teams, thus taking part in the DataChallange 

see [here](https://datachallenge-n.github.io/?autoSlide=0#/info/2) 

The issue is, that if you only start working with the data on Monday, you might have a hard time to do substantial progress till Wednesday. Since you are interested in earning the 1 ECTS, I strongly recommend you to do some analysis before Monday, even if the DataChallenge part is not a prerequisite to earning the ECTS.

**Comment by dinigi** [comment] 2022-06-15 13:30
Hi Nils, alright, sorry for the misunderstanding. I will take a look this
weekend and see how far I get. Unfortunately I couldn't take more than
monday and tuesday off from work (I don't necessarily need the ECTS tho)

**Comment by ratnanil** [comment] 2022-06-22 07:27
Since you regretfully can't take place in the hackdays, I will close this issue. Maybe next year!

**Closed as completed by ratnanil** 2022-06-22 07:27 UTC
Labels: contact-form, bachelor, IUNR, DataChallenge-submitted

**Comment by dinigi** [comment] 2022-10-11 07:31
Hi Nils, thanks for following up. Yes, I am very much interested in
participating and just returned you the NDA.

**Comment by ratnanil** [comment] 2022-10-11 14:52
Hey Diego

Thank you for your message, but the Data Challenge is long passed!

Cheers,

Nils

**Comment by dinigi** [comment] 2022-10-12 06:17
Hi Nils, I haven't written anything :)
